---
- name: role test
  hosts: testserver 
  remote_user: jeet
  
  tasks:
    - include_role:
        name: jeet
    - include_role:
        name: opatch_update
    - include_role:
        name: check_patch
    - include_role:
        name: SPB_apply
     
